name: Create UNL Json

on:
  push:
    branches: [mankins/automate]
    # paths:
    #   - "data/unl-raw.yaml"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without uploading to GCP"
        required: false
        default: "false"

permissions:
  contents: write # for creating a release
  id-token: write # for GCP OIDC
  actions: read

jobs:
  publish:
    name: Build UNL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js (or your CLI environment)
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install CLI
        run: |
          cd scripts/xrpl-cli
          pnpm install --frozen-lockfile

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Generate expiration and timestamp
        id: meta
        run: |
          TS=$(date -u +"%Y%m%d%H%M")
          if date -d "+4 months" >/dev/null 2>&1; then
            EXP=$(date -d "+4 months" +"%Y-%m-%d")
          else
            EXP=$(date -v+4m +"%Y-%m-%d")
          fi
          echo "ts=$TS" >> $GITHUB_OUTPUT
          echo "exp=$EXP" >> $GITHUB_OUTPUT

      - name: Generate UNL
        run: |
          node scripts/xrpl-cli/src/xrplf-cli.js unl generate \
            --validators="data/unl-raw.yaml" \
            --expiration="${{ steps.meta.outputs.exp }}" \
            --quiet \
            --output="unl-${{ steps.meta.outputs.ts }}.json"

      - name: Upload to GCP (if not dry run)
        if: ${{ github.event.inputs.dry_run != 'true' && steps.meta.outputs.ts != '' }}
        run: |
          gsutil cp "unl-${{ steps.meta.outputs.ts }}.json" gs://xrplf-unl/unl/unl-${{ steps.meta.outputs.ts }}.json
